import json
from typing import Dict, List

from openai import OpenAI


def _format_chunks(chunks: List[Dict]) -> str:
    lines = []
    for i, chunk in enumerate(chunks, start=1):
        lines.append(
            f"{i}. [{chunk['source']}, page {chunk['page_number']}]\n{chunk['content']}"
        )
    return "\n\n".join(lines)


def detect_hallucination(question: str, answer: str, chunks: List[Dict]) -> Dict:
    client = OpenAI()
    context_block = _format_chunks(chunks)
    system_prompt = """
You are a hallucination detector for a RAG system.
You will be given: a question, an answer generated by an AI, and the source chunks that were retrieved.
Your job is to verify whether every factual claim in the answer is directly supported by the source chunks.
Respond ONLY in JSON: {"hallucinated": true/false, "detail": "<brief explanation>"}
Do not add any preamble or markdown.
""".strip()

    user_payload = {
        "question": question,
        "answer": answer,
        "chunks": context_block,
    }

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        temperature=0,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": json.dumps(user_payload)},
        ],
    )
    raw = response.choices[0].message.content or "{}"
    parsed = json.loads(raw)
    return {
        "hallucinated": bool(parsed.get("hallucinated", False)),
        "detail": str(parsed.get("detail", "No detail provided.")),
    }
